# Change these first
owner: roo7k1d # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository
assignees:
  - Roo7K1d

sites:
  - name: Rootk1d.xyz
    url: https://rootk1d.xyz
    icon: https://cdn.discordapp.com/attachments/742731876170465310/896683113239937064/RootK1d.png
  - name: Discord FunTasticBot
    check: "udp-ping"
    url: https://rootk1d.xyz
    port: 2222
    icon: https://cdn.discordapp.com/attachments/742731876170465310/896682890073612348/images.png
  - name: PaD-Organizer Demo Page
    url: https://rootk1d.xyz/pad-demo
    icon: https://cdn.discordapp.com/attachments/742731876170465310/896685452080320562/pad_ico.png
  - name: RP-Police-Database Demo Page
    url: https://rootk1d.xyz/police
    icon: https://cdn.discordapp.com/attachments/742731876170465310/896686450811232256/police_ico.png


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.rootk1d.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://camo.githubusercontent.com/3decb51956fb910a92f2c59227261efc8349be135f20e92c93ba423f25cc7970/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3832303431363232343030353538363934352f3838373034313037323830313338363536362f67697475625f70726f66696c652e706e67
  name: RootK1d Services Status
  introTitle: "Services Uptime Monitor"
  introMessage: This lists all my publicly available projects and services.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://rootk1d.xyz
    - title: Discord
      href: https://discord.gg/QQaWvMkFbs
    - title: GitHub
      href: https://github.com/$OWNER
      
workflowSchedule:
  graphs: "*/2 * * * *"
  responseTime: "*/2 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/2 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
